### ISSUE TITLE
Add support for client certificate as credentials

### ISSUE THREAD

**Issue by anirudhbagri** [tomasbjerre/violation-comments-to-bitbucket-server-lib#11]
Currently, The lib supports two types of authentication, namely

1. Username & Password
2. Private Access Token

Can we add support for client certificate as authentication?
This can be done by using client certs from Keystore.

https://github.com/jenkinsci/violation-comments-to-stash-plugin/issues/71

**Comment by tomasbjerre** [comment]
Perhaps, not something I have done before. PR:s are welcome.

**Comment by anirudhbagri** [comment]
I am not very much into Java development, but it looks like some modification is required around this [line](https://github.com/tomasbjerre/violation-comments-to-bitbucket-server-lib/blob/75188041b22e0c4e2d8d5674aa408be090204bca/src/main/java/se/bjurr/violations/comments/bitbucketserver/lib/client/BitbucketServerInvoker.java#L109) and this [question on StackOverflow](https://stackoverflow.com/questions/21223084/how-do-i-use-an-ssl-client-certificate-with-apache-httpclient) might help anyone who tries to implement this.

**Comment by anirudhbagri** [comment]
Added PR #12 related to this.
